version: '3.8'

services:
  nginx_proxy:
    image: nginx
    container_name: nginx-proxy-reverse
    depends_on:
      - user_service
      - task_service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - user_service
      - task_service
    

# Runs the user service
  user_service:
    image: user_service
    container_name: user_service_container
    
  
  # Runs the task service
  task_service:
    image: task_service
    container_name: task_service_container

